### ISSUE TITLE
Password verification fails

### ISSUE THREAD

**Issue by papadenis** [vishnumaiea/R30X-Fingerprint-Sensor-Library#3]
I'm using a GROW R311. Checking the default password never passes, but nevertheless, the functions work further: for example, enrolling new fingers you can do.

> Command string = verpwd
> First param = ffffffff
> 
> 
> Sent packet = EF-1-FF-FF-FF-FF-1-0-7-13-FF-FF-FF-FF-4-17
> txInstructionCode = 13
> txDataBufferLength = 4
> txPacketLengthL = 7
> 
> Reading response.
> Checksums match success.
> Received = 0-1D
> Received L = 1D
> Calculated = 0-1D
> Calculated L = 1D
> Received packet = EF-1-FF-FF-FF-FF-7-0-3-13-0-1D
> Data stream = none
> rxConfirmationCode = 13
> rxDataBufferLength = 0
> rxPacketLengthL = 3
> rxPacketLength[] = 0-3
> Password is not correct.
> Current Password = FFFFFFFF
> rxConfirmationCode = 13
> response == 19
> ...........................

**Comment by vishnumaiea** [comment]
Will look into it this weekend. But IIRC, the default password set from factory is 0xFFFFFFFF. If you have ever changed the password, the verification can fail while trying to verify with the default password without passing one.

**Comment by vishnumaiea** [comment]
This is issue has been fixed. I was using explicitly added device password for verification in the example sketch, instead of the user configured one.
